# Generated by Django 4.0.3 on 2022-04-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Businessinfo',
            fields=[
                ('idbusinessinfo', models.AutoField(db_column='IdBusinessInfo', primary_key=True, serialize=False)),
                ('clientname', models.CharField(blank=True, db_column='ClientName', max_length=45, null=True)),
                ('week', models.CharField(blank=True, db_column='Week', max_length=20, null=True)),
                ('estimated_load_date', models.DateField(blank=True, db_column='Estimated_Load_Date', null=True)),
                ('pre_etd', models.DateField(blank=True, db_column='Pre_ETD', null=True)),
                ('etd', models.DateField(blank=True, db_column='ETD', null=True)),
                ('eta', models.DateField(blank=True, db_column='ETA', null=True)),
                ('vessel_voyage', models.CharField(db_column='Vessel_Voyage', max_length=45)),
                ('pol', models.CharField(db_column='POL', max_length=20)),
                ('pod', models.CharField(db_column='POD', max_length=20)),
                ('businessinfocol', models.CharField(blank=True, db_column='BusinessInfocol', max_length=200, null=True)),
                ('numctrs', models.IntegerField(db_column='NumCtrs')),
                ('type_ctrs', models.CharField(db_column='Type_Ctrs', max_length=10)),
                ('booking_no', models.CharField(db_column='Booking_No', max_length=45)),
                ('master_no', models.CharField(blank=True, db_column='Master_No', max_length=45, null=True)),
                ('num_hbls', models.IntegerField(blank=True, db_column='Num_HBLs', null=True)),
                ('container_no', models.CharField(blank=True, db_column='Container_No', max_length=45, null=True)),
                ('shipping_line', models.CharField(db_column='Shipping_Line', max_length=20)),
                ('freeddday', models.IntegerField(db_column='FreeDDday')),
                ('cost_org', models.FloatField(blank=True, db_column='Cost_Org', null=True)),
                ('sale_org', models.FloatField(blank=True, db_column='Sale_Org', null=True)),
                ('set_org', models.FloatField(blank=True, db_column='Set_Org', null=True)),
                ('local_org', models.FloatField(blank=True, db_column='Local_Org', null=True)),
                ('venta_dest', models.FloatField(blank=True, db_column='Venta_Dest', null=True)),
                ('costhbl_dest_description', models.CharField(blank=True, db_column='CostHBL_Dest_Description', max_length=45, null=True)),
                ('costhbl_dest', models.FloatField(blank=True, db_column='CostHBL_Dest', null=True)),
                ('costhbl_dest_status', models.CharField(db_column='CostHBL_Dest_Status', max_length=10)),
                ('topaid_org_description', models.CharField(blank=True, db_column='Topaid_Org_Description', max_length=45, null=True)),
                ('topaid_org', models.FloatField(blank=True, db_column='Topaid_Org', null=True)),
                ('topaid_status', models.CharField(db_column='Topaid_Status', max_length=10)),
                ('toinvoice_dest_description', models.CharField(blank=True, db_column='ToInvoice_Dest_Description', max_length=45, null=True)),
                ('toinvoice_dest', models.FloatField(blank=True, db_column='ToInvoice_Dest', null=True)),
                ('toinvoice_dest_status', models.CharField(db_column='ToInvoice_Dest_Status', max_length=10)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('hbl_canjeado_status', models.CharField(db_column='HBL_Canjeado_Status', max_length=10)),
                ('devolution_ctrs_inidate', models.DateField(blank=True, db_column='Devolution_Ctrs_IniDate', null=True)),
                ('devolution_ctrs_findate', models.DateField(blank=True, db_column='Devolution_Ctrs_FinDate', null=True)),
                ('operation_status', models.CharField(db_column='Operation_Status', max_length=10)),
                ('bl_type', models.CharField(blank=True, db_column='BL_Type', max_length=3, null=True)),
                ('release_type', models.CharField(blank=True, db_column='Release_Type', max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('user_pwd', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
