# Generated by Django 4.0.3 on 2022-04-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='mblfile',
            field=models.FileField(blank=True, max_length='150', null=True, upload_to='mbl/'),
        ),
    ]
