# Generated by Django 4.0.3 on 2022-04-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
    ]
