# Generated by Django 4.0.3 on 2022-04-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_userinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='id',
            field=models.IntegerField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
