# Generated by Django 4.0.3 on 2022-04-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_businessinfo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteInfo',
            fields=[
                ('id', models.CharField(db_column='id', max_length=45, primary_key=True, serialize=False)),
                ('clientname', models.CharField(db_column='ClientName', max_length=45)),
                ('clientrut', models.CharField(db_column='ClientRut', max_length=20)),
                ('clientgiro', models.CharField(db_column='ClientGiro', max_length=200)),
                ('clientaddress', models.CharField(db_column='ClientAddress', max_length=200)),
                ('clientcity', models.CharField(db_column='ClientCity', max_length=45)),
                ('clientstate', models.CharField(db_column='ClientState', max_length=45)),
                ('clientcontact', models.CharField(db_column='ClientContact', max_length=45)),
            ],
        ),
    ]
