# Generated by Django 4.0.3 on 2022-04-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_businessinfo_hblfiles_alter_businessinfo_mblfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='hblfiles',
            field=models.FileField(blank=True, db_column='HBLFiles', max_length='150', null=True, upload_to='hbl/%Y%m'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='mblfile',
            field=models.FileField(blank=True, db_column='MBLFile', max_length='150', null=True, upload_to='mbl/%Y%m'),
        ),
    ]
