# Generated by Django 4.0.3 on 2022-04-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_businessinfo_dp_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='hbls_canjeados',
            field=models.FileField(blank=True, db_column='HBLs_Canjeados', null=True, upload_to='HBLCNJDs-%Y%m/'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='hp_invoice',
            field=models.FileField(blank=True, db_column='HP_Invoice', null=True, upload_to='HPIs-%Y%m/'),
        ),
    ]
