# Generated by Django 4.0.3 on 2022-04-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_businessinfo_hbls_canjeados_businessinfo_hp_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='dp_voucher',
            field=models.FileField(blank=True, db_column='DP_Voucher', null=True, upload_to='DPVs-%Y%m/'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='hp_voucher',
            field=models.FileField(blank=True, db_column='HP_Voucher', null=True, upload_to='HPVs-%Y%m/'),
        ),
    ]
