# Generated by Django 4.0.3 on 2022-04-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_businessinfo_hbls_firmados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='first_hbl_no',
            field=models.CharField(blank=True, db_column='First_Hbl_No', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='hbl_memo',
            field=models.CharField(blank=True, db_column='Hbl_Memo', max_length=45, null=True),
        ),
    ]
